apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-frontend
  template:
    metadata:
      labels:
        app: metrics-frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        ports:
        - containerPort: 80
